spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
  datasource:
    name: demo
    url: jdbc:derby:E:/test/db/demo_db;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    